### ISSUE TITLE
Updated tp  but timezone is unable to be set.  

### ISSUE THREAD

**Issue by lgreerduo** [Tautulli/Tautulli-Docker#17]
Up'd the container and was greeted with the following error:

`Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 38, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    import activity_handler
  File "/app/tautulli/plexpy/activity_handler.py", line 24, in <module>
    import activity_processor
  File "/app/tautulli/plexpy/activity_processor.py", line 21, in <module>
    import database
  File "/app/tautulli/plexpy/database.py", line 24, in <module>
    import logger
  File "/app/tautulli/plexpy/logger.py", line 30, in <module>
    import helpers
  File "/app/tautulli/plexpy/helpers.py", line 48, in <module>
    from plexpy.api2 import API2
  File "/app/tautulli/plexpy/api2.py", line 39, in <module>
    import notification_handler
  File "/app/tautulli/plexpy/notification_handler.py", line 43, in <module>
    from newsletter_handler import notify as notify_newsletter
  File "/app/tautulli/plexpy/newsletter_handler.py", line 29, in <module>
    NEWSLETTER_SCHED = BackgroundScheduler()
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 82, in __init__
    self.configure(gconfig, **options)
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 121, in configur                                                                                                                  e
    self._configure(config)
  File "/app/tautulli/lib/apscheduler/schedulers/background.py", line 29, in _co                                                                                                                  nfigure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 689, in _configu                                                                                                                  re
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/tautulli/lib/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/tautulli/lib/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'`

In order to resolve this, an environmental variable is required. I added the following as I am near Denver:

`    environment:
      - TZ=America/Denver`

After the above was added, a successful up of the container was had.

**Comment by lgreerduo** [comment]
As stated above, issue was resolved by adding the TZ environmental variable.

**Comment by pconwell** [comment]
I am having this issue and adding the timezone is not fixing the issue.

Until the most recent update, I was using the following configuration which was working fine:

```
environment:
    - TZ=${TZ:-$(cat /etc/timezone 2>/dev/null)}
```

That stopped working, so I came here and saw the above solution so I tried to manually specify the timezone. However, the below configuration also does not work.

```
environment:
    - TZ=American/Chicago
```

Here is the error I get with either timezone configuration:

```
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 38, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    import activity_handler
  File "/app/tautulli/plexpy/activity_handler.py", line 24, in <module>
    import activity_processor
  File "/app/tautulli/plexpy/activity_processor.py", line 21, in <module>
    import database
  File "/app/tautulli/plexpy/database.py", line 24, in <module>
    import logger
  File "/app/tautulli/plexpy/logger.py", line 30, in <module>
    import helpers
  File "/app/tautulli/plexpy/helpers.py", line 48, in <module>
    from plexpy.api2 import API2
  File "/app/tautulli/plexpy/api2.py", line 39, in <module>
    import notification_handler
  File "/app/tautulli/plexpy/notification_handler.py", line 43, in <module>
    from newsletter_handler import notify as notify_newsletter
  File "/app/tautulli/plexpy/newsletter_handler.py", line 29, in <module>
    NEWSLETTER_SCHED = BackgroundScheduler()
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 82, in __init__
    self.configure(gconfig, **options)
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 121, in configure
    self._configure(config)
  File "/app/tautulli/lib/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 689, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/tautulli/lib/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/tautulli/lib/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

**Comment by samwiseg0** [comment]
@pconwell Issues are not the place for support, as explained in the README. Please use one of the [support options](https://tautulli.com/#support) available, with Discord being preferred.

**Comment by pconwell** [comment]
@samwiseg0 I don't see this as a support issue - it appears to be a code issue (i.e. a bug). It is giving an error that the timezone configuration cannot be found. I have tried two different ways to configure the timezone and neither are working. My previous configuration that included the timezone was working but has recently stopped working.

EDIT: Turn out I'm an idiot... image is working fine. I was using `etc/timezone` which is not used by alpine, and I was manually entering `American/...` instead of `America/...`

**Comment by samwiseg0** [comment]
@pconwell Please use one of the support options available, with Discord being preferred.

**Comment by TheMeanCanEHdian** [comment]
10M+ pulls of the docker would seem to indicate this is an issue with your setup not with the code. Use one of the support options and we can try and help see what is wrong.

**Comment by D4ndellion** [comment]
limiting yourselves to realtime support in a chat service where messages are lost in less than a day, and which are not googlable is not very useful for people who experience the same problem, and you might be creating _more_ work rather than less due to all the duplicate issues you'll need to resolve.

In my case it was that I had quotes around my timezone, which broken in some update
