### ISSUE TITLE
Can not find any timezone configuration

### ISSUE THREAD

**Issue by lusu007** [Tautulli/Tautulli-Docker#20]
Hello,

I have added TauTulli to my docker-compose.yml.
```
version: '3'
services:
  plex:
    container_name: plex
    build:
      context: ./build/plex
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400/tcp"
      - "33443:33443/tcp"
    volumes:
      - "./data/plex/config:/config"
      - "./data/plex/transcode:/transcode"
      - "./data/plex/data:/data"
    environment:
      - HOSTNAME="PLEXPERT"
      - TZ="Europe/Berlin"
      # Get a token for initial configuration on https://www.plex.tv/claim/
      # Add your token BEFORE running "docker-compose up"
      - PLEX_CLAIM="claim-YPMt7FFxm2f5XvgAhxhq"
  tautulli:
    container_name: tautulli
    image: tautulli/tautulli
    ports:
      - "8181:8181/tcp"
    volumes:
      - "./data/plex/config/Library/Application Support/Plex Media Server/Logs:/plex_logs:ro"
      - "./data/tautulli/config:/config"
    environment:
      - TZ="Europe/Berlin"
```

When starting TauTulli I get the following error: 
```
Traceback (most recent call last):
  File "/app/tautulli/Tautulli.py", line 38, in <module>
    import plexpy
  File "/app/tautulli/plexpy/__init__.py", line 37, in <module>
    import activity_handler
  File "/app/tautulli/plexpy/activity_handler.py", line 24, in <module>
    import activity_processor
  File "/app/tautulli/plexpy/activity_processor.py", line 21, in <module>
    import database
  File "/app/tautulli/plexpy/database.py", line 24, in <module>
    import logger
  File "/app/tautulli/plexpy/logger.py", line 30, in <module>
    import helpers
  File "/app/tautulli/plexpy/helpers.py", line 48, in <module>
    from plexpy.api2 import API2
  File "/app/tautulli/plexpy/api2.py", line 39, in <module>
    import notification_handler
  File "/app/tautulli/plexpy/notification_handler.py", line 43, in <module>
    from newsletter_handler import notify as notify_newsletter
  File "/app/tautulli/plexpy/newsletter_handler.py", line 29, in <module>
    NEWSLETTER_SCHED = BackgroundScheduler()
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 82, in __init__
    self.configure(gconfig, **options)
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 121, in configure
    self._configure(config)
  File "/app/tautulli/lib/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/tautulli/lib/apscheduler/schedulers/base.py", line 689, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/tautulli/lib/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/tautulli/lib/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

I think tzdata is not installed inside this image. Or is it my fault?

**Comment by Arcanemagus** [comment]
Please use one of the available [support options](https://tautulli.com/#support), as described in [Asking for Support](https://github.com/Tautulli/Tautulli-Wiki/wiki/Asking-for-Support). Discord is greatly preferred as it's faster for both you and us 😉.

----

You may also want to review a Markdown guide such as:
* [GitHub](https://help.github.com/en/articles/basic-writing-and-formatting-syntax)
* [Discord](https://support.discordapp.com/hc/en-us/articles/210298617-Markdown-Text-101-Chat-Formatting-Bold-Italic-Underline-)
