### ISSUE TITLE
Container won't start. ASCII error.

### ISSUE THREAD

**Issue by mil1i** [Tautulli/Tautulli-Docker#7]
The docker container no longer works for me at all. I was using linuxserver/plexpy and that was working. But it appears to have updated to the newest build and no longer starts. The tautulli/tautulli docker will not start for me, with the same issue. I am on a CentOS 7 host. 

I've attempted adding the -v /run, does not make a difference.  I've tried creating the docker as privileged.

The below is the error that repeats in the logs when it's attempting to start. Does anyone know what the issue is with the docker containers right now?

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
Traceback (most recent call last):
  File "/app/plexpy/PlexPy.py", line 35, in <module>
    import plexpy
  File "/app/plexpy/plexpy/__init__.py", line 59, in <module>
    SCHED = BackgroundScheduler()
  File "/app/plexpy/lib/apscheduler/schedulers/base.py", line 61, in __init__
    self.configure(gconfig, **options)
  File "/app/plexpy/lib/apscheduler/schedulers/base.py", line 95, in configure
    self._configure(config)
  File "/app/plexpy/lib/apscheduler/schedulers/background.py", line 27, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/app/plexpy/lib/apscheduler/schedulers/base.py", line 576, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/app/plexpy/lib/tzlocal/unix.py", line 108, in get_localzone
    _cache_tz = _get_localzone()
  File "/app/plexpy/lib/tzlocal/unix.py", line 41, in _get_localzone
    return _tz_from_env(tzenv)
  File "/app/plexpy/lib/tzlocal/unix.py", line 19, in _tz_from_env
    tz = pytz.timezone(tzenv)
  File "/app/plexpy/lib/pytz/__init__.py", line 167, in timezone
    zone = ascii(zone)
  File "/app/plexpy/lib/pytz/__init__.py", line 71, in ascii
    return s.encode('ASCII')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)
```

**Comment by TheMeanCanEHdian** [comment]
When was it last working for you and when did you update?

**Comment by mil1i** [comment]
I last used the linuxserver/plexpy last week and it worked. I just did a pull today, and created a new one and it gave the above error.

I have never got the tautulli/tautulli docker to start. Same error as above.

**Comment by JonnyWong16** [comment]
What timezone are you passing with the environment variable?

**Comment by mil1i** [comment]
`docker create --name=tautulli -h mil-ms.tautulli --restart=unless-stopped --net msnet --ip 172.30.0.11 -v /opt/plex/tautulli:/config -v /opt/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro -e PUID=1000 -e PGID=1000 -e TZ=”America/Denver” -p 8181:8181 tautulli/tautulli:latest`

**Comment by mil1i** [comment]
Ha! Omg. Just like that you made me realize the issue. It didn't like the quotations. Which is weird because all of my other containers I have used the quotes and had no issues.

Thank you! It started after removing the quotes.
